name: Publish with NODE_AUTH_TOKEN

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.4.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@signal-meaning'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build package
        run: npm run build
        
      - name: Run tests
        run: npm test
        
      - name: Configure npm authentication with NODE_AUTH_TOKEN
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@signal-meaning:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "NODE_AUTH_TOKEN content:"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          echo "@signal-meaning:registry=https://npm.pkg.github.com" >> .npmrc
          cat .npmrc
          echo ""
          echo "Testing authentication:"
          npm whoami --registry https://npm.pkg.github.com || echo "Whoami failed"
        
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
